--[[
脚本名字: RemoteNames
脚本文件: RemoteNames.lua
脚本类型: ModuleScript
Studio放置路径: ReplicatedStorage/Shared/RemoteNames
]]

local RemoteNames = {
    RootFolder = "Events",
    CurrencyEventsFolder = "CurrencyEvents",
    SystemEventsFolder = "SystemEvents",
    BrainrotEventsFolder = "BrainrotEvents",
    Currency = {
        CoinChanged = "CoinChanged",
        RequestCoinSync = "RequestCoinSync",
    },
    System = {
        HomeAssigned = "HomeAssigned",
        LikeTip = "LikeTip",
        PromptFavoritePlace = "PromptFavoritePlace",
        FavoritePlacePromptStarted = "FavoritePlacePromptStarted",
        FavoritePlacePromptResult = "FavoritePlacePromptResult",
        SocialStateSync = "SocialStateSync",
        RequestSocialStateSync = "RequestSocialStateSync",
        FriendBonusSync = "FriendBonusSync",
        RequestFriendBonusSync = "RequestFriendBonusSync",
        RequestShopStateSync = "RequestShopStateSync",
        RequestQuickTeleport = "RequestQuickTeleport",
        ClaimCashFeedback = "ClaimCashFeedback",
        RebirthStateSync = "RebirthStateSync",
        RequestRebirthStateSync = "RequestRebirthStateSync",
        RequestRebirth = "RequestRebirth",
        RebirthFeedback = "RebirthFeedback",
        RequestHomeExpansion = "RequestHomeExpansion",
        HomeExpansionFeedback = "HomeExpansionFeedback",
        SpecialEventStateSync = "SpecialEventStateSync",
        RequestSpecialEventStateSync = "RequestSpecialEventStateSync",
        LaunchPowerStateSync = "LaunchPowerStateSync",
        RequestLaunchPowerStateSync = "RequestLaunchPowerStateSync",
        RequestLaunchPowerUpgrade = "RequestLaunchPowerUpgrade",
        RequestStudioResetLaunchPower = "RequestStudioResetLaunchPower",
        RequestStudioBossDebugAction = "RequestStudioBossDebugAction",
        StudioBossDebugFeedback = "StudioBossDebugFeedback",
        LaunchPowerFeedback = "LaunchPowerFeedback",
        JetpackStateSync = "JetpackStateSync",
        RequestJetpackStateSync = "RequestJetpackStateSync",
        RequestJetpackCoinPurchase = "RequestJetpackCoinPurchase",
        RequestJetpackEquip = "RequestJetpackEquip",
        JetpackFeedback = "JetpackFeedback",
        SettingsStateSync = "SettingsStateSync",
        RequestSettingsStateSync = "RequestSettingsStateSync",
        RequestSettingsUpdate = "RequestSettingsUpdate",
        GroupRewardStateSync = "GroupRewardStateSync",
        RequestGroupRewardStateSync = "RequestGroupRewardStateSync",
        RequestGroupRewardClaim = "RequestGroupRewardClaim",
        GroupRewardFeedback = "GroupRewardFeedback",
        IdleCoinStateSync = "IdleCoinStateSync",
        RequestIdleCoinStateSync = "RequestIdleCoinStateSync",
        RequestIdleCoinClaim = "RequestIdleCoinClaim",
        RequestIdleCoinClaim10Purchase = "RequestIdleCoinClaim10Purchase",
        PromptIdleCoinClaim10Purchase = "PromptIdleCoinClaim10Purchase",
        RequestIdleCoinClaim10PurchaseClosed = "RequestIdleCoinClaim10PurchaseClosed",
        IdleCoinFeedback = "IdleCoinFeedback",
        SevenDayLoginRewardStateSync = "SevenDayLoginRewardStateSync",
        RequestSevenDayLoginRewardStateSync = "RequestSevenDayLoginRewardStateSync",
        RequestSevenDayLoginRewardClaim = "RequestSevenDayLoginRewardClaim",
        StarterPackStateSync = "StarterPackStateSync",
        RequestStarterPackStateSync = "RequestStarterPackStateSync",
        RequestSeaHazardDeath = "RequestSeaHazardDeath",
        StealTip = "StealTip",
        BrainrotClaimTip = "BrainrotClaimTip",
        RequestLuckyBlockOpen = "RequestLuckyBlockOpen",
        LuckyBlockFeedback = "LuckyBlockFeedback",
    },
    Brainrot = {
        BrainrotStateSync = "BrainrotStateSync",
        RequestBrainrotStateSync = "RequestBrainrotStateSync",
        RequestBrainrotUpgrade = "RequestBrainrotUpgrade",
        BrainrotUpgradeFeedback = "BrainrotUpgradeFeedback",
        RequestBrainrotSell = "RequestBrainrotSell",
        BrainrotSellFeedback = "BrainrotSellFeedback",
        BrainrotGiftOffer = "BrainrotGiftOffer",
        RequestBrainrotGiftDecision = "RequestBrainrotGiftDecision",
        BrainrotGiftFeedback = "BrainrotGiftFeedback",
        RequestStudioBrainrotGrant = "RequestStudioBrainrotGrant",
        StudioBrainrotGrantFeedback = "StudioBrainrotGrantFeedback",
        PromptBrainrotStealPurchase = "PromptBrainrotStealPurchase",
        RequestBrainrotStealPurchaseClosed = "RequestBrainrotStealPurchaseClosed",
        BrainrotStealFeedback = "BrainrotStealFeedback",
        RequestCarryUpgrade = "RequestCarryUpgrade",
        CarryUpgradeFeedback = "CarryUpgradeFeedback",
        BossStateSync = "BossStateSync",
        RequestDropCarriedWorldBrainrot = "RequestDropCarriedWorldBrainrot",
        BossWarning = "BossWarning",
        BossKnockback = "BossKnockback",
    },
}

return RemoteNames
